const jwt = require('jsonwebtoken');


// decode,verify,generate

const value = {
    name: 'rajan',
    acountnumber: 123456
}
//jwt
//sign is the function to generate the token
const token = jwt.sign(value, 'secret')
console.log(token)
//this token is generated by using this secret and hence this token can only be verified by using this secret 